#!/bin/sh

# xclip
pacman -Qi xclip >/dev/null 2>&1 || sudo pacman -S --noconfirm xclip

# nnn - the unorthodox terminal file manager
pacman -Qi nnn >/dev/null 2>&1 || sudo pacman -S --noconfirm nnn
[ -d $HOME/.config/nnn/plugins ] || mkdir -p $HOME/.config/nnn/plugins
ln -sf $(realpath config/nnn/plugins/*) $HOME/.config/nnn/plugins

# dmenu
pacman -Qi dmenu >/dev/null 2>&1 || sudo pacman -S --noconfirm dmenu

# pulsemixer
pacman -Qi pulsemixer >/dev/null 2>&1 || sudo pacman -S --noconfirm pulsemixer

# i3lock
pacman -Qi i3lock >/dev/null 2>&1 || sudo pacman -S --noconfirm i3lock

# cmus
pacman -Qi cmus >/dev/null 2>&1 || sudo pacman -S --noconfirm cmus

# imagemagick
pacman -Qi imagemagick >/dev/null 2>&1 || sudo pacman -S --noconfirm imagemagick

# mpv
pacman -Qi mpv >/dev/null 2>&1 || sudo pacman -S --noconfirm mpv

# youtube-dl
pacman -Qi youtube-dl >/dev/null 2>&1 || sudo pacman -S --noconfirm youtube-dl

# feh
pacman -Qi feh >/dev/null 2>&1 || sudo pacman -S --noconfirm feh

# poppler
pacman -Qi poppler >/dev/null 2>&1 || sudo pacman -S --noconfirm poppler

# ffmpegthumbnailer
pacman -Qi ffmpegthumbnailer >/dev/null 2>&1 || sudo pacman -S --noconfirm ffmpegthumbnailer

# sxiv
pacman -Qi sxiv >/dev/null 2>&1 || sudo pacman -S --noconfirm sxiv

# dunst
pacman -Qi dunst >/dev/null 2>&1 || sudo pacman -S --noconfirm dunst
[ -d $HOME/.config/dunst ] || mkdir -p $HOME/.config/dunst
ln -sf $(realpath config/dunst/dunstrc) $HOME/.config/dunst/

# sxhkd
pacman -Qi sxhkd >/dev/null 2>&1 || sudo pacman -S --noconfirm sxhkd
[ -d $HOME/.config/sxhkd ] || mkdir -p $HOME/.config/sxhkd
ln -sf $(realpath config/sxhkd/sxhkdrc) $HOME/.config/sxhkd/

# maim
pacman -Qi maim >/dev/null 2>&1 || sudo pacman -S --noconfirm maim

# zathura
pacman -Qi zathura >/dev/null 2>&1 || sudo pacman -S --noconfirm zathura
pacman -Qi zathura-djvu >/dev/null 2>&1 || sudo pacman -S --noconfirm zathura-djvu
pacman -Qi zathura-pdf-mupdf >/dev/null 2>&1 || sudo pacman -S --noconfirm zathura-pdf-mupdf
[ -d $HOME/.config/zathura ] || mkdir -p $HOME/.config/zathura
ln -sf $(realpath config/zathura/zathurarc) $HOME/.config/zathura/

# aria2
pacman -Qi aria2 >/dev/null 2>&1 || sudo pacman -S --noconfirm aria2

# man
pacman -Qi man >/dev/null 2>&1 || sudo pacman -S --noconfirm man

# pandoc
pacman -Qi pandoc >/dev/null 2>&1 || sudo pacman -S --noconfirm pandoc

# texlive
pacman -Qg texlive-most >/dev/null 2>&1 || sudo pacman -S --noconfirm texlive-most
pacman -Qg texlive-lang >/dev/null 2>&1 || sudo pacman -S --noconfirm texlive-lang

# xdg-user-dirs
pacman -Qi xdg-user-dirs >/dev/null 2>&1 || sudo pacman -S --noconfirm xdg-user-dirs
ln -sf $(realpath config/user-dirs.dirs) $HOME/.config/user-dirs.dirs
ln -sf $(realpath config/user-dirs.locale) $HOME/.config/user-dirs.locale
[ -d $HOME/dls ] || mkdir -p $HOME/dls
[ -d $HOME/shr ] || mkdir -p $HOME/shr
[ -d $HOME/docs ] || mkdir -p $HOME/docs
[ -d $HOME/mus ] || mkdir -p $HOME/mus
[ -d $HOME/pics ] || mkdir -p $HOME/pics
[ -d $HOME/vids ] || mkdir -p $HOME/vids
[ -d $HOME/cons ] || mkdir -p $HOME/cons
[ -d $HOME/repos ] || mkdir -p $HOME/repos
[ -d $HOME/qemu ] || mkdir -p $HOME/qemu
xdg-user-dirs-update

# noto-fonts
pacman -Qi noto-fonts >/dev/null 2>&1 || sudo pacman -S --noconfirm noto-fonts
pacman -Qi noto-fonts-cjk >/dev/null 2>&1 || sudo pacman -S --noconfirm noto-fonts-cjk
pacman -Qi noto-fonts-emoji >/dev/null 2>&1 || sudo pacman -S --noconfirm noto-fonts-emoji
pacman -Qi noto-fonts-extra >/dev/null 2>&1 || sudo pacman -S --noconfirm noto-fonts-extra

# ttf-iosevka
yay -Qi ttf-iosevka >/dev/null 2>&1 || yay -S --noconfirm ttf-iosevka

# font-config
[ -d $HOME/.config/fontconfig ] || mkdir -p $HOME/.config/fontconfig
ln -sf $(realpath config/fontconfig/fonts.conf) $HOME/.config/fontconfig/

# applications (desktop-files)
[ -d $HOME/.local/share/applications ] || mkdir -p $HOME/.local/share/applications
ln -sf $(realpath applications/*) $HOME/.local/share/applications

# binaries
[ -d $HOME/.local/bin ] || mkdir -p $HOME/.local/bin
ln -sf $(realpath bin/*) $HOME/.local/bin
chmod +x bin/*

# link config files
ln -sf $(realpath config/bashrc) $HOME/.bashrc
ln -sf $(realpath config/vimrc) $HOME/.vimrc
ln -sf $(realpath config/xinitrc) $HOME/.xinitrc

# link inside .config
ln -sf $(realpath config/mimeapps.list) $HOME/.config/mimeapps.list
