#!/usr/bin/python

import json
import subprocess


def main():
    process = subprocess.Popen(['git', 'annex', 'metadata', '--json'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = process.communicate()

    json_data = {}

    output = ''

    for data in stdout.decode('utf-8').split('\n'):
        if not data:
            continue
        
        data = json.loads(data)

        if data['file'] not in json_data:
            json_data[data['file']] = data

            tags = data['fields'].get('tag', [])
            tags = ' '.join(tags)

            output += '{} {}\n'.format(
                    data['file'], tags)
    
    fzf = subprocess.Popen(['fzf', '-e'], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    stdout, stderr = fzf.communicate(output.encode('utf-8'))

    selected_file = stdout.decode('utf-8').split()[0]
    print(stdout)

    opened_process = subprocess.Popen(['xdg-open', selected_file], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    stdout, stderr = opened_process.communicate()


if __name__ == '__main__':
    main()
