#!/usr/bin/env bash

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

if [ -s "$selection" ]; then
    arr=($(tr '\0' '\n' < "$selection"))
else
    arr=($1)
fi

printf "%s\n" "${arr[@]}"
printf "tags: "
read ans

tags=''

IFS=$' '

for tag in $ans
do
    if [[ $tag == *"="* ]]; then
        field=$(echo "$tag" | sed -e "s/\=$//")
        tags="$tags --remove $field"
    else
        tags="$tags --untag $tag"
    fi
done

IFS=$'\n'

for file in ${arr[@]}
do
    command="git annex metadata \"$file\" $tags"
    bash -c $command
done
