# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# enable vi style editing in bash
set -o vi

# disable history
#set +o history

export EDITOR=nvim
export BROWSER=qutebrowser

# nnn
export NNN_FIFO=/tmp/nnn.fifo
export NNN_PLUG='w:preview-tabbed;c:cmount;u:cumount;l:wallpaper;L:lock'

export PASSWORD_STORE_DIR=~/annex/pass

# run 'startx' command
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
	exec startx;
fi
