# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# enable vi style editing in bash
set -o vi

# aliases
alias gitall="git remote | awk -F, '\$1 != \"upstream\"' | xargs -L1 -I R git push R --all"

# disable history
#set +o history

source $HOME/.bashrc_nnn

export EDITOR=nvim
export BROWSER=qutebrowser

export PASSWORD_STORE_DIR=~/annex/pass

# run 'startx' command
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
	exec startx;
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
