# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# alias ranger
alias ranger='ranger --cachedir=$HOME/.tmp/ranger'

# enable vi style editing in bash
set -o vi

# run 'startx' command
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
	exec startx;
fi

export EDITOR=nvim
