# Home Computer
if [ $(hostname) = "naukan-home" ]; then
    xrandr --output DVI-D-0 --auto --output DP-0 --auto --left-of DVI-D-0
fi


# Set $PATH variable
export PATH="$PATH:$HOME/.local/bin"

# Start statusbar items
$HOME/.local/bin/dwm_statusbar

# Start global shortcuts
sxhkd &

# Start notification system
dunst &

# Start nm-applet
nm-applet &

# Start transmission
transmission-daemon &

# Show background wallpaper
feh --bg-fill $HOME/.wallpaper.png

# Fix Java Blank Screen
export _JAVA_AWT_WM_NONREPARENTING=1

# For Android SDK
export ANDROID_HOME=$HOME/apps/android/sdk/
export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator"

# Keyboard Layout
setxkbmap -layout "us,ru,kz"

# Loop dwm
while true; do
    dwm 1>/dev/null 2>&1
done
