# Home Computer
if [ $(hostname) = "naukan-home" ]; then
    xrandr --output DVI-D-0 --auto --output DP-0 --auto --right-of DVI-D-0
fi

# Set $PATH variable
export PATH="$PATH:$HOME/.local/bin"

# Start dwmblocks
dwmblocks &

# Start global shortcuts
sxhkd &

# Start notification system
dunst &

# Start Emacs as a daemon
emacs --daemon &

# Show background wallpaper
feh --bg-fill $HOME/.wallpaper

# Fix Java Blank Screen
export _JAVA_AWT_WM_NONREPARENTING=1

# Keyboard Layout
setxkbmap -layout "us,ru" -option grp:caps_toggle

# Loop dwm
while true; do
    dwm 1>/dev/null 2>&1
done
