FILE=~/.xinitrc_local

# Set $PATH variable
export PATH="$PATH:$HOME/.local/bin"

# Start dwmblocks
dwmblocks &

# Start global shortcuts
sxhkd &

# Start notification system
dunst &

# Start Emacs as a daemon
emacs --daemon &

# Show background wallpaper
feh --bg-fill $HOME/.wallpaper

# Fix Java Blank Screen
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit

# Keyboard Layout
setxkbmap -layout "us,ru" -option grp:caps_toggle

# Start nmapplet
nm-applet &

# Connect to bridge
nmcli conn up enp2s0

# .xinitrc_local
# xrandr --output DVI-D-0 --primary --auto --panning 1920x1080+1920+0 --output HDMI-0 --mode 1920x1080 --panning 1920x1080+0+0
if [ -f "$FILE" ]; then
    source $FILE
fi

# Loop dwm
while true; do
    dwm 1>/dev/null 2>&1
done
